version: 2
jobs:
  npm-cache:
      docker:
        - image: cypress/base:8

      working_directory: ~/mboyz
      steps:
        - checkout
        - restore_cache:
            keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

        - run:
            name: Install local dependencies
            command: npm ci

        - save_cache:
            paths:
              - ~/.npm
              - ~/.cache
              - node_modules
            key: v1-dependencies-{{ checksum "package-lock.json" }}

  build:
    docker:
      - image: cypress/base:8

    working_directory: ~/chrome-extension
    steps:
      - checkout
      - restore_cache:
                keys:
                - v1-dependencies-{{ checksum "package-lock.json" }}
                # fallback to using the latest cache if no exact match is found
                - v1-dependencies-
      - run:
          name: Test
          command: npm run test

workflows:
  version: 2
  build:
    jobs:
      - npm-cache
      - build:
          requires:
            - npm-cache